// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHiHHNVVmJOfmSWCU0bSUAW0LHuY5-vis',
    appId: '1:343498599521:web:49b979beab67e669f8ce20',
    messagingSenderId: '343498599521',
    projectId: 'lojistik-f4f2e',
    authDomain: 'lojistik-f4f2e.firebaseapp.com',
    storageBucket: 'lojistik-f4f2e.firebasestorage.app',
    measurementId: 'G-MNMPFKFZXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPzwgMOZt4U3zCPsWXgnvXAYaW9kHZiw',
    appId: '1:343498599521:android:0d226a0ab9906d1bf8ce20',
    messagingSenderId: '343498599521',
    projectId: 'lojistik-f4f2e',
    storageBucket: 'lojistik-f4f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Lsi6TfP6PdjmRBpEkqN1aIeylb9Fia4',
    appId: '1:343498599521:ios:aef5352c45b26619f8ce20',
    messagingSenderId: '343498599521',
    projectId: 'lojistik-f4f2e',
    storageBucket: 'lojistik-f4f2e.firebasestorage.app',
    iosBundleId: 'com.example.logisticOfficial',
  );
}
